/** Listas de termos e frases bloqueadas — importadas pelo motor de filtro. */

export const BLOCKED_TERMS_PT = [
  "caralho",
  "porra",
  "merda",
  "bosta",
  "buceta",
  "xota",
  "xoxota",
  "xana",
  "cu",
  "cuzao",
  "cuzão",
  "foda",
  "foder",
  "fuder",
  "fude",
  "fodido",
  "fodida",
  "fodase",
  "foda-se",
  "fdp",
  "puta",
  "putaria",
  "puto",
  "putinha",
  "putinho",
  "piranha",
  "vadia",
  "vadiagem",
  "vadiado",
  "viado",
  "viadinho",
  "bicha",
  "boiola",
  "traveco",
  "desgraca",
  "desgraça",
  "desgracado",
  "desgraçado",
  "arrombado",
  "arrombada",
  "babaca",
  "otario",
  "otário",
  "imbecil",
  "idiota",
  "retardado",
  "retardada",
  "mongol",
  "nazista",
  "nazismo",
  "hitler",
  "estupido",
  "estúpido",
  "estupida",
  "estúpida",
  "estupro",
  "estuprar",
  "vagabundo",
  "vagabunda",
  "pica",
  "pau",
  "pinto",
  "rola",
  "rabo",
  "broxa",
  "punheta",
  "punheteiro",
  "siririca",
  "vsf",
  "vtnc",
  "tnc",
  "pqp",
  "krl",
  "krlh",
  "caralh",
  "cacete",
  "cacetada",
  "sacana",
  "safada",
  "safado",
  "canalha",
  "escroto",
  "escrota",
  "boceta",
  "bunda",
  "bundao",
  "bundão",
  "cuzuda",
  "cuzudo",
  "vtmnc",
  "noobzao",
  "macaca",
  "macaco",
  "macacada",
  "macacudo",
  "sexo",
  "sexual",
  "transar",
  "trepar",
  "prostituta",
  "prostituicao",
  "prostituto",
  "pedofilo",
  "pedofilia",
  "necrofilia",
  "zoofilia",
  "incesto",
  "sodomia",
  "orgia",
  "pornografia",
  "porno",
  "pornô",
  "masturbacao",
  "masturbar",
  "ejacular",
  "gozar",
  "gozada",
  "penis",
  "pênis",
  "vagina",
  "clitoris",
  "clitóris",
  "anus",
  "ânus",
  "anal",
  "oral",
  "felação",
  "felacao",
  "chupar",
  "lamber",
  "nua",
  "nu",
  "pelada",
  "pelado",
  "nudez",
  "nudes",
  "nude",
  "onlyfans",
  "escort",
  "garota de programa",
  "negrinho",
  "negrinha",
  "pretinho",
  "pretinha",
  "peituda",
  "peitudo",
  "tetuda",
  "tetudo",
  "vaginuda",
  "vaginudo",
  "bucetuda",
  "bucetudo",
  "estuprada",
  "estrupada",
  "estrupadq",
  "estrupro",
  "corno",
  "corna",
  "chifrudo",
  "chifruda",
  "lixao",
  "lixão",
  "nojinho",
  "nojento",
  "asqueroso",
  "maldito",
  "maldita",
  "desgraçado",
  "tarado",
  "tarada",
  "pervertido",
  "pervertida",
  "assediar",
  "assédio",
  "assediando",
  "gostosa",
  "gostoso",
  "safadeza",
  "tesao",
  "tesão",
  "excitado",
  "excitada",
  "erotico",
  "erótico",
  "hentai",
  "camgirl",
  "cam boy",
  "sugar daddy",
  "deepfake",
  "revenge porn",
  "cp",
  "lolita",
  "gore",
  "suicidio",
  "suicídio",
  "se matar",
  "mata voce",
  "mata você",
  "morre",
  "morra",
  "vou te matar",
  "te mato",
  "ameaça",
  "ameacar",
  "estourar",
  "estoura",
  "linchar",
  "linchamento",
  "supremacia",
  "supremacista",
  "holocausto",
  "swastika",
  "suastica",
  "suástica",
  "heil",
  "kkk",
  "trafico",
  "tráfico",
  "drogas ilegais",
  "cocaina",
  "cocaína",
  "crack",
  "maconha",
  "heroína",
  "heroina",
];

export const BLOCKED_TERMS_EN = [
  "fuck",
  "fucking",
  "fucker",
  "fucked",
  "motherfucker",
  "shit",
  "shitty",
  "bullshit",
  "bitch",
  "bastard",
  "asshole",
  "dick",
  "cock",
  "pussy",
  "cunt",
  "whore",
  "slut",
  "nigger",
  "nigga",
  "faggot",
  "fag",
  "retard",
  "retarded",
  "wtf",
  "stfu",
  "lmfao",
  "douchebag",
  "scumbag",
  "jackass",
  "wanker",
  "bollocks",
  "prick",
  "douche",
  "twat",
  "rape",
  "rapist",
  "pedophile",
  "pedo",
  "sex",
  "porn",
  "porno",
  "nude",
  "nudes",
  "naked",
  "blowjob",
  "handjob",
  "cumshot",
  "orgasm",
  "dildo",
  "vibrator",
  "hentai",
  "milf",
  "threesome",
  "gangbang",
  "bestiality",
  "incest",
  "necrophilia",
  "kys",
  "kill yourself",
  "suicide",
  "lynch",
  "nazi",
  "hitler",
  "holocaust",
  "swastika",
  "white power",
  "heil",
  "coon",
  "spic",
  "chink",
  "kike",
  "tranny",
  "shemale",
  "rapebait",
  "deepthroat",
  "onlyfans",
  "camgirl",
  "revenge porn",
  "gore",
  "cp",
  "loli",
  "lolicon",
];

export const BLOCKED_PHRASES = [
  "filho da puta",
  "filha da puta",
  "vai se foder",
  "vai se fuder",
  "va se foder",
  "va se fuder",
  "vai tomar no cu",
  "tomar no cu",
  "se foder",
  "se fuder",
  "filho da p",
  "vai se f",
  "vai a merda",
  "vai pro inferno",
  "piece of shit",
  "go fuck",
  "fuck you",
  "fuck off",
  "suck my",
  "eat shit",
  "son of a bitch",
  "sexo anal",
  "vamos nos comer",
  "vamos transar",
  "preta macaca",
  "preto macaco",
  "macaco preto",
  "macaca preta",
  "vai tomar",
  "nos comer",
  "me come",
  "te como",
  "quero te comer",
  "vou te comer",
  "peituda e aberta",
  "prima gostosa",
  "passa numero",
  "me passa numero",
  "me passa número",
  "penis adentrando",
  "pênis adentrando",
  "adentrando seu",
  "quero dormir quentinho",
  "meu penis",
  "meu pênis",
  "meu cu",
  "meu cú",
  "meu pau",
  "meu pinto",
  "minha rola",
  "sua rola",
  "kill yourself",
  "go die",
  "i will kill",
  "white power",
  "heil hitler",
  "manda nudes",
  "manda nude",
  "envia nudes",
  "envia nude",
  "mostra os peitos",
  "mostra a buceta",
  "tira a roupa",
  "vem sentar",
  "sentar no",
  "chupa meu",
  "chupa minha",
  "chupa meu pau",
  "chupa minha rola",
  "vou te estuprar",
  "vou te violar",
  "te estupro",
  "te violo",
  "sua puta",
  "sua vadia",
  "sua piranha",
  "filha da",
  "filho da",
  "tomar no seu",
  "no seu cu",
  "enfia no cu",
  "enfia no seu",
  "vai tomar no seu",
  "seu lixo",
  "sua lixo",
  "morre infeliz",
  "vai morrer",
  "te arrombo",
  "vou arrombar",
];

export const BLOCKED_COMPACT_PATTERNS: RegExp[] = [
  /f+u+d+[aeiou]?[a-z]*/,
  /p+u+t+[aeiou]?[a-z]*/,
  /m+a+c+a+c+[ao]/,
  /caralh[oao]?/,
  /porr[aao]?/,
  /merd[aao]?/,
  /vadi[aao]/,
  /sex[o0]/,
  /n+[i1!|]+g+[gq0]+[ae4]+/,
  /n+[i1!|]+g+[gq0]+e*r/,
  /f+[u0]+c+k/,
  /p+e+i+t+[oa]?ud[aao]?/,
  /t+e+t+[oa]?ud[aao]?/,
  /v+a+g+i+n+[oa]?ud[aao]?/,
  /b+u+c+e+t+[oa]?ud[aao]?/,
  /e+s+t+r?u+p+r+[ao]?[dq]?/,
  /p+e+d+o+f/,
  /p+e+n+i+s/,
  /p+[i1!|]+n+t+[o0](?![a-z0-9])/,
  /r+[o0]+l+[a4@](?![a-z0-9])/,
  /c+u+[z7]+[a4@]?[o0]?/,
  /b+[i1!|]+t+c+h/,
  /w+h+[o0]+r+e/,
  /c+[u0]+n+t/,
  /a+s+s+h+[o0]+l+e/,
  /k+[i1!|]+l+l+[y0]+[u0]+[r0]+s+[e3]+l+f/,
  /s+u+[i1!|]+c+[i1!|]+d+e/,
  /h+[e3]+[i1!|]+l+h+[i1!|]+t+l+[e3]+r/,
  /n+[a4@]+z+[i1!|]/,
  /p+[o0]+rn+[o0]?/,
  /h+[e3]+n+t+[a4@][i1!|]/,
  /g+[o0]+z+[a4@r]/,
  /t+o+m+[a4@]r+n+[o0]+c+[u0]/,
  /v+[a4@][i1!|]+s+[e3]+f+[o0]+d/,
  /m+[a4@]c+[a4@][c4]+[o0]/,
];

export const BLOCKED_STEMS = [
  "peitud",
  "tetud",
  "vaginud",
  "bucetud",
  "estupr",
  "estrupr",
  "pedofil",
  "pornograf",
  "nigg",
  "niigg",
  "fagg",
  "retard",
  "suicid",
  "nazis",
  "hitler",
  "whore",
  "prostitu",
];

/** Termos que só bloqueiam como palavra isolada (evita falsos positivos). */
export const BOUNDARY_ONLY_TERMS = new Set([
  "cu",
  "nu",
  "anal",
  "oral",
  "pau",
  "pinto",
  "rola",
  "sex",
  "sexo",
  "rabo",
  "cp",
  "kkk",
  "gore",
  "morre",
  "morra",
  "heil",
]);

export const BLOCKED_TERMS = [...BLOCKED_TERMS_PT, ...BLOCKED_TERMS_EN];
