import type { Prisma, StoreItemCategory } from "@prisma/client";

export type ShopCatalogItem = {
  slug: string;
  name: string;
  description: string;
  cost: number;
  category: StoreItemCategory;
  imageUrl?: string;
  isPremiumOnly?: boolean;
  isPermanent?: boolean;
  metadata?: Prisma.InputJsonValue;
};

export const SHOP_CATALOG: ShopCatalogItem[] = [
  {
    slug: "title-biomas",
    name: "Mestre dos Biomas",
    description: "Título exclusivo para quem domina ciências da natureza.",
    cost: 120,
    category: "TITLE",
    metadata: { titleText: "Mestre dos Biomas" },
  },
  {
    slug: "title-dev-senior",
    name: "Dev Sênior",
    description: "Mostre sua maestria em tecnologia no perfil.",
    cost: 150,
    category: "TITLE",
    metadata: { titleText: "Dev Sênior" },
  },
  {
    slug: "title-estudioso",
    name: "Estudioso Imparável",
    description: "Para quem não para de aprender.",
    cost: 100,
    category: "TITLE",
    metadata: { titleText: "Estudioso Imparável" },
  },
  {
    slug: "border-cyan",
    name: "Borda Ciano",
    description: "Linha sólida ciano — borda comum para iniciantes.",
    cost: 40,
    category: "AVATAR_BORDER",
    metadata: { borderId: "border-cyan", rarity: "common" },
  },
  {
    slug: "border-aurora",
    name: "Borda Aurora",
    description: "Gradiente estático roxo e rosa — raridade rara.",
    cost: 80,
    category: "AVATAR_BORDER",
    metadata: { borderId: "border-aurora", rarity: "rare" },
  },
  {
    slug: "border-gold",
    name: "Borda Dourada",
    description: "Gradiente dourado estático — raridade rara.",
    cost: 120,
    category: "AVATAR_BORDER",
    metadata: { borderId: "border-gold", rarity: "rare" },
  },
  {
    slug: "border-crystal",
    name: "Moldura Cristal",
    description: "Moldura de perfil com brilho gelo — cosmético lendário.",
    cost: 160,
    category: "AVATAR_BORDER",
    metadata: { borderId: "border-crystal", rarity: "legendary" },
  },
  {
    slug: "theme-hexavante",
    name: "Tema Hexavante",
    description: "Visual padrão da plataforma — azul e teal original.",
    cost: 0,
    category: "THEME",
    isPermanent: true,
    metadata: { themeId: "default" },
  },
  {
    slug: "theme-cyberpunk",
    name: "Tema Dark Cyberpunk",
    description: "Neon fuchsia, violeta e ciano em toda a interface.",
    cost: 200,
    category: "THEME",
    metadata: { themeId: "cyberpunk" },
  },
  {
    slug: "theme-hacker",
    name: "Tema Hacker / Matrix",
    description: "Estética terminal verde para foco total.",
    cost: 180,
    category: "THEME",
    metadata: { themeId: "hacker" },
  },
  {
    slug: "theme-obsidian",
    name: "Tema Obsidian Dark",
    description: "Dark extremo com acentos prata e índigo.",
    cost: 220,
    category: "THEME",
    metadata: { themeId: "obsidian" },
  },
  {
    slug: "theme-sunset",
    name: "Tema Sunset Glow",
    description: "Laranja quente, rosa e crepúsculo dourado — sidebar e UI alinhadas.",
    cost: 190,
    category: "THEME",
    metadata: { themeId: "sunset" },
  },
  {
    slug: "theme-ocean",
    name: "Tema Deep Ocean",
    description: "Azul profundo com reflexos aquáticos em toda a interface.",
    cost: 170,
    category: "THEME",
    metadata: { themeId: "ocean" },
  },
  {
    slug: "theme-sakura",
    name: "Tema Sakura Bloom",
    description: "Rosa suave inspirado em cerejeiras — visual calmo e elegante.",
    cost: 210,
    category: "THEME",
    metadata: { themeId: "sakura" },
  },
  {
    slug: "theme-midnight",
    name: "Tema Midnight Violet",
    description: "Roxo profundo para sessões noturnas de estudo.",
    cost: 200,
    category: "THEME",
    metadata: { themeId: "midnight" },
  },
  {
    slug: "theme-amber",
    name: "Tema Golden Amber",
    description: "Dourado elegante com sidebar em tons âmbar.",
    cost: 180,
    category: "THEME",
    metadata: { themeId: "amber" },
  },
  {
    slug: "theme-snow",
    name: "Tema Neve Branca",
    description: "Interface clara e limpa — branco com acentos azuis.",
    cost: 0,
    category: "THEME",
    isPermanent: true,
    metadata: { themeId: "snow" },
  },
  {
    slug: "theme-daylight",
    name: "Tema Luz do Dia",
    description: "Cinza suave e teal para estudar com luz natural.",
    cost: 150,
    category: "THEME",
    metadata: { themeId: "daylight" },
  },
  {
    slug: "theme-cream",
    name: "Tema Creme Suave",
    description: "Off-white quente com detalhes dourados confortáveis.",
    cost: 160,
    category: "THEME",
    metadata: { themeId: "cream" },
  },
  {
    slug: "theme-pearl",
    name: "Tema Pérola Clara",
    description: "Branco perolado com violeta delicado em toda a UI.",
    cost: 170,
    category: "THEME",
    metadata: { themeId: "pearl" },
  },
  {
    slug: "booster-rewards-24h",
    name: "Booster de Recompensas (24h)",
    description: "Dobra moedas e XP ganhos ao estudar por 24 horas.",
    cost: 90,
    category: "BOOSTER",
    isPermanent: false,
    metadata: { multiplier: 2, durationHours: 24, affects: ["coins", "xp"] },
  },
  {
    slug: "booster-xp-12h",
    name: "Booster de XP (12h)",
    description: "Dobra apenas o XP conquistado em simulados e cursos por 12 horas.",
    cost: 70,
    category: "BOOSTER",
    isPermanent: false,
    metadata: { multiplier: 2, durationHours: 12, affects: ["xp"] },
  },
  {
    slug: "booster-xp-48h",
    name: "Booster de XP (48h)",
    description: "Dobra o XP ganho por 48 horas — ideal para maratonas de estudo.",
    cost: 140,
    category: "BOOSTER",
    isPermanent: false,
    metadata: { multiplier: 2, durationHours: 48, affects: ["xp"] },
  },
  {
    slug: "cosmetic-spark-notes",
    name: "Adesivo Spark Notes",
    description: "Cosmético decorativo para o perfil.",
    cost: 60,
    category: "COSMETIC",
    metadata: { cosmeticType: "sticker", icon: "sparkles" },
  },
  {
    slug: "cosmetic-icon-flame",
    name: "Ícone Chama",
    description: "Ícone exclusivo de perfil para estudantes em alta performance.",
    cost: 85,
    category: "COSMETIC",
    metadata: { cosmeticType: "profile_icon", iconId: "icon-flame" },
  },
  {
    slug: "cosmetic-icon-brain",
    name: "Ícone Mente Brilhante",
    description: "Ícone de perfil que destaca seu foco intelectual.",
    cost: 95,
    category: "COSMETIC",
    metadata: { cosmeticType: "profile_icon", iconId: "icon-brain" },
  },
  {
    slug: "cosmetic-icon-trophy",
    name: "Ícone Troféu",
    description: "Mostre suas conquistas com este ícone lendário no perfil.",
    cost: 110,
    category: "COSMETIC",
    metadata: { cosmeticType: "profile_icon", iconId: "icon-trophy" },
  },
  {
    slug: "pass-premium-exams-7d",
    name: "Passe Simulados Premium (7 dias)",
    description: "Acesso antecipado a simulados exclusivos Premium por 7 dias, sem assinatura.",
    cost: 200,
    category: "PASS",
    isPermanent: false,
    metadata: { passType: "premium_exams", durationDays: 7 },
  },
  {
    slug: "pass-early-logica",
    name: "Passe Lançamento — Lógica Avançada",
    description:
      "Libera acesso antecipado ao simulado Desafio Premium — Lógica Avançada por 14 dias.",
    cost: 150,
    category: "PASS",
    isPermanent: false,
    metadata: {
      passType: "early_exam",
      examSlug: "desafio-premium-logica-avancada",
      durationDays: 14,
    },
  },
  {
    slug: "pack-revisao-logica",
    name: "Pacote Revisão — Lógica de Programação",
    description:
      "Conjunto de 10 questões selecionadas sobre lógica e algoritmos para revisão focada.",
    cost: 75,
    category: "REVIEW_PACK",
    isPermanent: false,
    metadata: {
      topic: "Lógica de Programação",
      examSlugs: ["logica-programacao-basica"],
      questionCount: 10,
      durationDays: 14,
    },
  },
  {
    slug: "pack-revisao-premium",
    name: "Pacote Revisão — Desafio Premium",
    description: "Questões selecionadas do simulado premium para treino intensivo por 7 dias.",
    cost: 100,
    category: "REVIEW_PACK",
    isPermanent: false,
    metadata: {
      topic: "Lógica Avançada",
      examSlugs: ["desafio-premium-logica-avancada"],
      questionCount: 8,
      durationDays: 7,
    },
  },
  {
    slug: "title-premium-crown",
    name: "Coroa Premium",
    description: "Título exclusivo para assinantes Premium.",
    cost: 0,
    category: "TITLE",
    isPremiumOnly: true,
    metadata: { titleText: "Coroa Premium" },
  },
  {
    slug: "border-premium-neon",
    name: "Borda Neon Premium",
    description: "Chroma animado lendário — exclusivo para assinantes.",
    cost: 0,
    category: "AVATAR_BORDER",
    isPremiumOnly: true,
    metadata: { borderId: "border-premium-neon", rarity: "legendary" },
  },
  {
    slug: "badge-foco",
    name: "Distintivo Foco Total",
    description: "Distintivo de perfil para quem mantém o foco nos estudos.",
    cost: 70,
    category: "BADGE",
    metadata: { badgeId: "badge-foco", rarity: "common" },
  },
  {
    slug: "badge-maratonista",
    name: "Distintivo Maratonista",
    description: "Mostre que você encara maratonas de estudo até o fim.",
    cost: 110,
    category: "BADGE",
    metadata: { badgeId: "badge-maratonista", rarity: "rare" },
  },
  {
    slug: "badge-mentor",
    name: "Distintivo Mentor",
    description: "Distintivo lendário para estudantes que ajudam a comunidade.",
    cost: 150,
    category: "BADGE",
    metadata: { badgeId: "badge-mentor", rarity: "legendary" },
  },
  {
    slug: "frame-neon",
    name: "Moldura Neon",
    description: "Moldura decorativa de perfil com brilho neon animado.",
    cost: 90,
    category: "FRAME",
    metadata: { frameId: "frame-neon", rarity: "rare" },
  },
  {
    slug: "frame-geometria",
    name: "Moldura Geometria",
    description: "Moldura de perfil com padrão geométrico minimalista.",
    cost: 80,
    category: "FRAME",
    metadata: { frameId: "frame-geometria", rarity: "common" },
  },
  {
    slug: "frame-madeira",
    name: "Moldura Madeira",
    description: "Moldura quente de perfil estilo madeira.",
    cost: 85,
    category: "FRAME",
    metadata: { frameId: "frame-madeira", rarity: "common" },
  },
  {
    slug: "emoji-pack-estudo",
    name: "Pack Emojis Estudo",
    description: "Conjunto de emojis exclusivos para comentários e mensagens.",
    cost: 60,
    category: "EMOJI_PACK",
    metadata: { emojiPackId: "emoji-pack-estudo", emojis: ["📚", "✏️", "🎯", "🧠", "🔥"] },
  },
  {
    slug: "emoji-pack-tech",
    name: "Pack Emojis Tech",
    description: "Emojis temáticos de tecnologia para sua comunicação.",
    cost: 75,
    category: "EMOJI_PACK",
    metadata: { emojiPackId: "emoji-pack-tech", emojis: ["💻", "⚙️", "🚀", "🐛", "🛡️"] },
  },
  {
    slug: "bg-galaxy",
    name: "Fundo Galaxy",
    description: "Fundo de perfil com gradiente cósmico estático.",
    cost: 120,
    category: "PROFILE_BACKGROUND",
    metadata: { backgroundId: "bg-galaxy", rarity: "rare" },
  },
  {
    slug: "bg-sunset-gradient",
    name: "Fundo Sunset",
    description: "Fundo de perfil com gradiente quente de crepúsculo.",
    cost: 100,
    category: "PROFILE_BACKGROUND",
    metadata: { backgroundId: "bg-sunset-gradient", rarity: "common" },
  },
  {
    slug: "bg-matrix",
    name: "Fundo Matrix",
    description: "Fundo de perfil estilo terminal verde.",
    cost: 110,
    category: "PROFILE_BACKGROUND",
    metadata: { backgroundId: "bg-matrix", rarity: "rare" },
  },

  // ── Títulos ──────────────────────────────────────────────────────────
  { slug: "title-dedicacao", name: "Dedicado", description: "Para quem nunca desiste.", cost: 80, category: "TITLE", metadata: { titleText: "Dedicado" } },
  { slug: "title-estratega", name: "Estratega", description: "Planeja antes de agir — em provas e na vida.", cost: 100, category: "TITLE", metadata: { titleText: "Estratega" } },
  { slug: "title-pioneiro", name: "Pioneiro", description: "O primeiro a concluir um curso completo.", cost: 90, category: "TITLE", metadata: { titleText: "Pioneiro" } },
  { slug: "title-guerreiro", name: "Guerreiro", description: "Persistência acima de tudo.", cost: 70, category: "TITLE", metadata: { titleText: "Guerreiro" } },
  { slug: "title-mestre-codigo", name: "Mestre do Código", description: "Domínio absoluto em programação.", cost: 160, category: "TITLE", metadata: { titleText: "Mestre do Código" } },
  { slug: "title-analista", name: "Analista", description: "Dados e lógica são seu idioma.", cost: 120, category: "TITLE", metadata: { titleText: "Analista" } },
  { slug: "title-cientista-dados", name: "Cientista de Dados", description: "Transforma números em histórias.", cost: 170, category: "TITLE", metadata: { titleText: "Cientista de Dados" } },
  { slug: "title-dev-fullstack", name: "Dev Full Stack", description: "Front e back sob controle.", cost: 150, category: "TITLE", metadata: { titleText: "Dev Full Stack" } },
  { slug: "title-designer-ux", name: "Designer UX", description: "Interfaces que encantam.", cost: 130, category: "TITLE", metadata: { titleText: "Designer UX" } },
  { slug: "title-engenheiro-cloud", name: "Engenheiro Cloud", description: "Escalabilidade é sua especialidade.", cost: 180, category: "TITLE", metadata: { titleText: "Engenheiro Cloud" } },
  { slug: "title-rei-matematica", name: "Rei da Matemática", description: "Equações não te assustam.", cost: 140, category: "TITLE", metadata: { titleText: "Rei da Matemática" } },
  { slug: "title-musa-redacao", name: "Musa da Redação", description: "Redação nota 1000.", cost: 130, category: "TITLE", metadata: { titleText: "Musa da Redação" } },
  { slug: "title-fenomeno-fisica", name: "Fenômeno da Física", description: "Newton teria inveja.", cost: 120, category: "TITLE", metadata: { titleText: "Fenômeno da Física" } },
  { slug: "title-alquimista", name: "Alquimista", description: "Transforma fórmulas em soluções.", cost: 110, category: "TITLE", metadata: { titleText: "Alquimista" } },
  { slug: "title-historiador", name: "Historiador", description: "O passado é seu campo de estudo.", cost: 90, category: "TITLE", metadata: { titleText: "Historiador" } },
  { slug: "title-geografo", name: "Geógrafo", description: "Mundos e mapas sob seu comando.", cost: 90, category: "TITLE", metadata: { titleText: "Geógrafo" } },
  { slug: "title-filosofo", name: "Filósofo", description: "Perguntas são seu combustível.", cost: 100, category: "TITLE", metadata: { titleText: "Filósofo" } },
  { slug: "title-sociologo", name: "Sociólogo", description: "Entende o mundo pelas relações.", cost: 100, category: "TITLE", metadata: { titleText: "Sociólogo" } },
  { slug: "title-poliglota", name: "Poliglota", description: "Fala várias línguas, resolve tudo.", cost: 160, category: "TITLE", metadata: { titleText: "Poliglota" } },
  { slug: "title-mentor", name: "Mentor", description: "Ajuda outros a alcançar o topo.", cost: 150, category: "TITLE", metadata: { titleText: "Mentor" } },
  { slug: "title-leitor-serial", name: "Leitor Serial", description: "Mais de 100 livros lidos.", cost: 120, category: "TITLE", metadata: { titleText: "Leitor Serial" } },
  { slug: "title-nota-10", name: "Nota 10", description: "Perfeição em provas.", cost: 140, category: "TITLE", metadata: { titleText: "Nota 10" } },
  { slug: "title-maratonista", name: "Maratonista", description: "Estuda sem parar.", cost: 110, category: "TITLE", metadata: { titleText: "Maratonista" } },
  { slug: "title-ecologista", name: "Ecologista", description: "Defende o planeta através do conhecimento.", cost: 100, category: "TITLE", metadata: { titleText: "Ecologista" } },
  { slug: "title-tech-lead", name: "Tech Lead", description: "Lidera equipes de tecnologia.", cost: 200, category: "TITLE", metadata: { titleText: "Tech Lead" } },
  { slug: "title-empresario", name: "Empreendedor", description: "Cria oportunidades onde outros veem problemas.", cost: 190, category: "TITLE", metadata: { titleText: "Empreendedor" } },
  { slug: "title-cientista", name: "Cientista", description: "Descobre o novo.", cost: 180, category: "TITLE", metadata: { titleText: "Cientista" } },
  { slug: "title-criador", name: "Criador", description: "Inventa soluções inovadoras.", cost: 150, category: "TITLE", metadata: { titleText: "Criador" } },
  { slug: "title-estrategista", name: "Estrategista", description: "Planeja cada passo com precisão.", cost: 170, category: "TITLE", metadata: { titleText: "Estrategista" } },
  { slug: "title-estudioso-elite", name: "Estudioso Elite", description: "O topo da dedicação acadêmica.", cost: 200, category: "TITLE", metadata: { titleText: "Estudioso Elite" } },

  // ── Molduras decorativas ─────────────────────────────────────────────
  { slug: "frame-fire", name: "Moldura Fogo", description: "Chamas douradas ao redor do perfil.", cost: 120, category: "FRAME", metadata: { frameId: "frame-fire", rarity: "rare" } },
  { slug: "frame-ice", name: "Moldura Gelo", description: "Bordas cristalinas e frias.", cost: 110, category: "FRAME", metadata: { frameId: "frame-ice", rarity: "rare" } },
  { slug: "frame-cyber", name: "Moldura Cyber", description: "Estética futurista e neon.", cost: 140, category: "FRAME", metadata: { frameId: "frame-cyber", rarity: "legendary" } },
  { slug: "frame-crystal", name: "Moldura Cristal", description: "Brilho etéreo de cristal.", cost: 130, category: "FRAME", metadata: { frameId: "frame-crystal", rarity: "rare" } },
  { slug: "frame-flower", name: "Moldura Flores", description: "Detalhes florais delicados.", cost: 90, category: "FRAME", metadata: { frameId: "frame-flower", rarity: "common" } },
  { slug: "frame-shadow", name: "Moldura Sombra", description: "Misteriosa e escura.", cost: 100, category: "FRAME", metadata: { frameId: "frame-shadow", rarity: "common" } },
  { slug: "frame-gold", name: "Moldura Ouro", description: "Luxo e elegância dourada.", cost: 150, category: "FRAME", metadata: { frameId: "frame-gold", rarity: "legendary" } },
  { slug: "frame-rainbow", name: "Moldura Arco-Íris", description: "Cores vibrantes do arco-íris.", cost: 110, category: "FRAME", metadata: { frameId: "frame-rainbow", rarity: "rare" } },
  { slug: "frame-dark", name: "Moldura Dark", description: "Preta e misteriosa.", cost: 80, category: "FRAME", metadata: { frameId: "frame-dark", rarity: "common" } },
  { slug: "frame-light", name: "Moldura Luz", description: "Clara e iluminada.", cost: 85, category: "FRAME", metadata: { frameId: "frame-light", rarity: "common" } },

  // ── Fundos de perfil ─────────────────────────────────────────────────
  { slug: "bg-aurora", name: "Fundo Aurora", description: "Aurora boreal verde e azul.", cost: 130, category: "PROFILE_BACKGROUND", metadata: { backgroundId: "bg-aurora", rarity: "rare" } },
  { slug: "bg-rain", name: "Fundo Chuva", description: "Gotas de chuva suaves.", cost: 90, category: "PROFILE_BACKGROUND", metadata: { backgroundId: "bg-rain", rarity: "common" } },
  { slug: "bg-beach", name: "Fundo Praia", description: "Areia e mar em sunset.", cost: 100, category: "PROFILE_BACKGROUND", metadata: { backgroundId: "bg-beach", rarity: "common" } },
  { slug: "bg-mountain", name: "Fundo Montanha", description: "Picos nevados ao amanhecer.", cost: 110, category: "PROFILE_BACKGROUND", metadata: { backgroundId: "bg-mountain", rarity: "rare" } },
  { slug: "bg-city", name: "Fundo Cidade", description: "Skyline noturno urbano.", cost: 100, category: "PROFILE_BACKGROUND", metadata: { backgroundId: "bg-city", rarity: "common" } },
  { slug: "bg-forest", name: "Fundo Floresta", description: "Verde profundo da natureza.", cost: 95, category: "PROFILE_BACKGROUND", metadata: { backgroundId: "bg-forest", rarity: "common" } },
  { slug: "bg-space", name: "Fundo Espaço", description: "Nebulosa e estrelas distantes.", cost: 140, category: "PROFILE_BACKGROUND", metadata: { backgroundId: "bg-space", rarity: "rare" } },
  { slug: "bg-electric", name: "Fundo Elétrico", description: "Descargas e raios neon.", cost: 120, category: "PROFILE_BACKGROUND", metadata: { backgroundId: "bg-electric", rarity: "rare" } },
  { slug: "bg-desert", name: "Fundo Deserto", description: "Dunas douradas ao pôr do sol.", cost: 95, category: "PROFILE_BACKGROUND", metadata: { backgroundId: "bg-desert", rarity: "common" } },
  { slug: "bg-underwater", name: "Fundo Subaquático", description: "Oceano profundo e azul.", cost: 115, category: "PROFILE_BACKGROUND", metadata: { backgroundId: "bg-underwater", rarity: "rare" } },

  // ── Molduras extras ──────────────────────────────────────────────────
  { slug: "frame-volcanic", name: "Moldura Vulcânica", description: "Lava derretida ao redor do perfil.", cost: 130, category: "FRAME", metadata: { frameId: "frame-volcanic", rarity: "rare" } },
  { slug: "frame-neon-purple", name: "Moldura Neon Roxo", description: "Brilho neon púrpura hipnótico.", cost: 115, category: "FRAME", metadata: { frameId: "frame-neon-purple", rarity: "rare" } },
  { slug: "frame-electric-blue", name: "Moldura Elétrica Azul", description: "Descargas azuis eletrizantes.", cost: 120, category: "FRAME", metadata: { frameId: "frame-electric-blue", rarity: "rare" } },
  { slug: "frame-royal", name: "Moldura Real", description: "Elegância real e imponente.", cost: 160, category: "FRAME", metadata: { frameId: "frame-royal", rarity: "legendary" } },
  { slug: "frame-mint", name: "Moldura Menta", description: "Refrescante e clean.", cost: 80, category: "FRAME", metadata: { frameId: "frame-mint", rarity: "common" } },
  { slug: "frame-rain", name: "Moldura Chuva", description: "Gotas de chuva caindo suavemente.", cost: 115, category: "FRAME", metadata: { frameId: "frame-rain", rarity: "rare" } },
  { slug: "frame-forest", name: "Moldura Floresta", description: "Folhas verdes flutuando na brisa.", cost: 115, category: "FRAME", metadata: { frameId: "frame-forest", rarity: "rare" } },

  // ── Ícones de perfil ──────────────────────────────────────────────────
  { slug: "icon-star", name: "Ícone Estrela", description: "Brilhe como uma estrela.", cost: 60, category: "COSMETIC", metadata: { cosmeticType: "profile_icon", iconId: "icon-star" } },
  { slug: "icon-rocket", name: "Ícone Foguete", description: "Dispare rumo ao sucesso.", cost: 70, category: "COSMETIC", metadata: { cosmeticType: "profile_icon", iconId: "icon-rocket" } },
  { slug: "icon-gem", name: "Ícone Gema", description: "Raro e precioso.", cost: 80, category: "COSMETIC", metadata: { cosmeticType: "profile_icon", iconId: "icon-gem" } },
  { slug: "icon-shield", name: "Ícone Escudo", description: "Proteção e coragem.", cost: 65, category: "COSMETIC", metadata: { cosmeticType: "profile_icon", iconId: "icon-shield" } },
  { slug: "icon-book", name: "Ícone Livro", description: "O conhecimento é poder.", cost: 55, category: "COSMETIC", metadata: { cosmeticType: "profile_icon", iconId: "icon-book" } },

  // ── Distintivos extras ───────────────────────────────────────────────
  { slug: "badge-ouro", name: "Distintivo Ouro", description: "Símbolo de excelência dourada.", cost: 130, category: "BADGE", metadata: { badgeId: "badge-ouro", rarity: "rare" } },
  { slug: "badge-diamante", name: "Distintivo Diamante", description: "Inquebrável e reluzente.", cost: 200, category: "BADGE", metadata: { badgeId: "badge-diamante", rarity: "legendary" } },
  { slug: "badge-cientista", name: "Distintivo Cientista", description: "Paixão pela descoberta.", cost: 100, category: "BADGE", metadata: { badgeId: "badge-cientista", rarity: "rare" } },
  { slug: "badge-artista", name: "Distintivo Artista", description: "Criatividade sem limites.", cost: 90, category: "BADGE", metadata: { badgeId: "badge-artista", rarity: "common" } },
  { slug: "badge-lider", name: "Distintivo Líder", description: "Inspira e comanda com EXAMPLE.", cost: 140, category: "BADGE", metadata: { badgeId: "badge-lider", rarity: "rare" } },

  // ── Pack de emojis extra ─────────────────────────────────────────────
  { slug: "emoji-pack-esportes", name: "Pack Emojis Esportes", description: "Emojis de esportes e atividades físicas.", cost: 55, category: "EMOJI_PACK", metadata: { emojiPackId: "emoji-pack-esportes", emojis: ["⚽", "🏀", "🏈", "🎾", "🏊"] } },
];

export const RETIRED_SHOP_CATEGORIES: StoreItemCategory[] = ["PET", "PET_COSMETIC"];

export const STORE_CATEGORY_LABELS: Record<StoreItemCategory, string> = {
  TITLE: "Títulos",
  AVATAR_BORDER: "Molduras de perfil",
  THEME: "Temas",
  COSMETIC: "Cosméticos",
  BOOSTER: "Boosters",
  PASS: "Passes",
  REVIEW_PACK: "Pacotes de revisão",
  PET: "Pets",
  PET_COSMETIC: "Acessórios de pet",
  BADGE: "Distintivos",
  FRAME: "Molduras decorativas",
  EMOJI_PACK: "Pacotes de emoji",
  PROFILE_BACKGROUND: "Fundos de perfil",
};

export const SHOP_FAIR_PLAY_NOTE =
  "A loja vende personalização e conveniência — nunca vantagem em provas. Boosters só aumentam XP e moedas; passes liberam acesso antecipado, não alteram notas.";

export const SHOP_EARN_COINS_HINTS = [
  { label: "Aula concluída", amount: 3 },
  { label: "Módulo concluído", amount: 10 },
  { label: "Curso concluído", amount: 25 },
  { label: "Questão correta no simulado", amount: 5 },
  { label: "Recompensa de liga (temporada)", amount: "variável" },
] as const;

export const SHOP_TAB_CATEGORIES: Record<
  "personalize" | "boosters" | "passes" | "review_packs" | "premium",
  StoreItemCategory[] | "premium"
> = {
  personalize: ["TITLE", "AVATAR_BORDER", "THEME", "COSMETIC", "BADGE", "FRAME", "EMOJI_PACK", "PROFILE_BACKGROUND"],
  boosters: ["BOOSTER"],
  passes: ["PASS"],
  review_packs: ["REVIEW_PACK"],
  premium: "premium",
};
