/** Classes CSS compartilhadas — seguem variáveis do tema equipado. */
export const themeUi = {
  tabNav: "hx-tab-nav",
  tabActive: "hx-tab-active",
  tabInactive: "hx-tab-inactive",
  segmentNav: "hx-segment-nav",
  themePanel: "hx-theme-panel",
  profileBanner: "hx-profile-banner",
  profileCard: "hx-profile-card",
  headerStat: "hx-header-stat",
  listItem: "hx-list-item",
  accentLink: "hx-accent-link",
  accentText: "hx-accent-text",
  accentSoft: "hx-accent-soft",
  progressTrack: "hx-progress-track",
  progressFill: "hx-progress-fill",
  textTitle: "hx-text-title",
  textBody: "hx-text-body",
  textMuted: "hx-text-muted",
  textSubtle: "hx-text-subtle",
  surfaceChip: "hx-surface-chip",
  filterActive: "hx-filter-pill-active",
  filterInactive: "hx-filter-pill-inactive",
  // Animation classes
  stagger: "stagger-children",
  cardEntrance: "card-entrance",
  hoverLift: "hover-lift",
  btnPress: "btn-press",
  inputFocus: "input-focus",
  skeletonPulse: "skeleton-pulse",
  toastEnter: "toast-enter",
  toastExit: "toast-exit",
  modalOverlayEnter: "modal-overlay-enter",
  modalOverlayExit: "modal-overlay-exit",
  modalContentEnter: "modal-content-enter",
  modalContentExit: "modal-content-exit",
  dropdownEnter: "dropdown-enter",
  dropdownExit: "dropdown-exit",
  pageEnter: "page-enter",
  pageExit: "page-exit",
  avatarHover: "avatar-hover",
  badgePulse: "badge-pulse",
  notificationDot: "notification-dot",
  focusRing: "focus-ring",
  transitionSmooth: "transition-smooth",
  transitionBounce: "transition-bounce",
  transitionSpring: "transition-spring",
} as const;
